### ISSUE TITLE
"FADE OUT" missing as stop mode

### ISSUE THREAD

**Issue by sammahoney** [westlicht/rc505-editor#3]
Hey. First off, thank you so much for creating this app (I use my RC-505 mostly for imported sample playback so it's a godsend).

Just a heads up that you don't have the "Fade Out" stop mode. Just needs adding to the middle of the array:

`EnumProperty *stopMode = createChild<EnumProperty>("Stop Mode", "StpMod", StringArray({"IMMEDIATE","FADE OUT","LOOP END"}));`

https://github.com/westlicht/rc505-editor/blob/master/Source/RC505.h#L493

Thanks again for all your hard work!

**Comment by westlicht** [comment]
implemented in 0.0.3
